# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/vehicle/registration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.common import date_pb2 as proto_dot_common_dot_date__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n proto/vehicle/registration.proto\x12\x07vehicle\x1a\x17proto/common/date.proto\"\xb5\x02\n\x0cRegistration\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\t\x12\x0b\n\x03vin\x18\x03 \x01(\t\x12\r\n\x05\x62rand\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\x0c\n\x04year\x18\x06 \x01(\x05\x12\x10\n\x08\x63\x61pacity\x18\x07 \x01(\x05\x12\r\n\x05\x63olor\x18\x08 \x01(\t\x12\x0c\n\x04\x66uel\x18\t \x01(\t\x12\x0c\n\x04kind\x18\n \x01(\t\x12\x13\n\x0bnum_seating\x18\x0b \x01(\x05\x12\x12\n\nown_weight\x18\x0c \x01(\x05\x12\x14\n\x0ctotal_weight\x18\r \x01(\x05\x12\x1a\n\x04\x64\x61te\x18\x0e \x01(\x0b\x32\x0c.common.Date\x12$\n\x0e\x66irst_reg_date\x18\x0f \x01(\x0b\x32\x0c.common.Date\x12\x10\n\x08\x63\x61tegory\x18\x10 \x01(\tB$Z\"github.com/opencars/schema/vehicleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.vehicle.registration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"github.com/opencars/schema/vehicle'
  _REGISTRATION._serialized_start=71
  _REGISTRATION._serialized_end=380
# @@protoc_insertion_point(module_scope)
