# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/koatuu/events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/koatuu/events.proto\x12\x06koatuu\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n\x0e\x44\x65\x63odingCalled\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08token_id\x18\x02 \x01(\t\x12\x12\n\ntoken_name\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12-\n\tcalled_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB#Z!github.com/opencars/schema/koatuub\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.koatuu.events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z!github.com/opencars/schema/koatuu'
  _DECODINGCALLED._serialized_start=71
  _DECODINGCALLED._serialized_end=203
# @@protoc_insertion_point(module_scope)
