# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/backoffice/events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/backoffice/events.proto\x12\nbackoffice\"&\n\x0f\x43ustomerBlocked\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\"(\n\x11\x43ustomerUnblocked\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\tB\'Z%github.com/opencars/schema/backofficeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.backoffice.events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z%github.com/opencars/schema/backoffice'
  _CUSTOMERBLOCKED._serialized_start=45
  _CUSTOMERBLOCKED._serialized_end=83
  _CUSTOMERUNBLOCKED._serialized_start=85
  _CUSTOMERUNBLOCKED._serialized_end=125
# @@protoc_insertion_point(module_scope)
