// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: proto/koatuu/events.proto

package koatuu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecodingCalled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenId   string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenName string                 `protobuf:"bytes,3,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	Code      string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	CalledAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=called_at,json=calledAt,proto3" json:"called_at,omitempty"`
}

func (x *DecodingCalled) Reset() {
	*x = DecodingCalled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_koatuu_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodingCalled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodingCalled) ProtoMessage() {}

func (x *DecodingCalled) ProtoReflect() protoreflect.Message {
	mi := &file_proto_koatuu_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodingCalled.ProtoReflect.Descriptor instead.
func (*DecodingCalled) Descriptor() ([]byte, []int) {
	return file_proto_koatuu_events_proto_rawDescGZIP(), []int{0}
}

func (x *DecodingCalled) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DecodingCalled) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *DecodingCalled) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *DecodingCalled) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DecodingCalled) GetCalledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CalledAt
	}
	return nil
}

var File_proto_koatuu_events_proto protoreflect.FileDescriptor

var file_proto_koatuu_events_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x6f, 0x61, 0x74, 0x75, 0x75, 0x2f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6b, 0x6f, 0x61,
	0x74, 0x75, 0x75, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x69, 0x6e,
	0x67, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x37,
	0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x64, 0x41, 0x74, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x61, 0x72, 0x73, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x6b, 0x6f, 0x61, 0x74, 0x75, 0x75, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_koatuu_events_proto_rawDescOnce sync.Once
	file_proto_koatuu_events_proto_rawDescData = file_proto_koatuu_events_proto_rawDesc
)

func file_proto_koatuu_events_proto_rawDescGZIP() []byte {
	file_proto_koatuu_events_proto_rawDescOnce.Do(func() {
		file_proto_koatuu_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_koatuu_events_proto_rawDescData)
	})
	return file_proto_koatuu_events_proto_rawDescData
}

var file_proto_koatuu_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_koatuu_events_proto_goTypes = []interface{}{
	(*DecodingCalled)(nil),        // 0: koatuu.DecodingCalled
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_proto_koatuu_events_proto_depIdxs = []int32{
	1, // 0: koatuu.DecodingCalled.called_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_koatuu_events_proto_init() }
func file_proto_koatuu_events_proto_init() {
	if File_proto_koatuu_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_koatuu_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodingCalled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_koatuu_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_koatuu_events_proto_goTypes,
		DependencyIndexes: file_proto_koatuu_events_proto_depIdxs,
		MessageInfos:      file_proto_koatuu_events_proto_msgTypes,
	}.Build()
	File_proto_koatuu_events_proto = out.File
	file_proto_koatuu_events_proto_rawDesc = nil
	file_proto_koatuu_events_proto_goTypes = nil
	file_proto_koatuu_events_proto_depIdxs = nil
}
