# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auction/auction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from proto.common import date_pb2 as proto_dot_common_dot_date__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/auction/auction.proto\x12\x07\x61uction\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17proto/common/date.proto\"\xd1\x05\n\x07\x41uction\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\x12\r\n\x05title\x18\x05 \x01(\t\x12\x0b\n\x03url\x18\x06 \x01(\t\x12\x13\n\x0binternal_id\x18\x07 \x01(\t\x12\x0f\n\x07\x61uction\x18\x08 \x01(\t\x12\x0e\n\x06seller\x18\t \x01(\t\x12\x12\n\nlot_number\x18\n \x01(\t\x12\r\n\x05price\x18\x0b \x01(\x05\x12\x0e\n\x06status\x18\x0c \x01(\t\x12\x12\n\nimage_urls\x18\r \x03(\t\x12\"\n\x0c\x64\x61te_of_sale\x18\x0e \x01(\x0b\x32\x0c.common.Date\x12\x0b\n\x03vin\x18\x0f \x01(\t\x12\x11\n\tcondition\x18\x10 \x01(\t\x12\x0e\n\x06\x65ngine\x18\x11 \x01(\t\x12\x0f\n\x07mileage\x18\x12 \x01(\x05\x12\x11\n\tdocuments\x18\x13 \x01(\t\x12\x10\n\x08location\x18\x14 \x01(\t\x12\x16\n\x0eprimary_damage\x18\x15 \x01(\t\x12\x18\n\x10secondary_damage\x18\x16 \x01(\t\x12\x1e\n\x16\x65stimated_retail_value\x18\x17 \x01(\x05\x12\x1d\n\x15\x65stimated_repair_cost\x18\x18 \x01(\x05\x12\x14\n\x0cgearbox_type\x18\x19 \x01(\t\x12\r\n\x05\x63olor\x18\x1a \x01(\t\x12\x18\n\x10wheel_drive_type\x18\x1b \x01(\t\x12\x0c\n\x04\x66uel\x18\x1c \x01(\t\x12\x0c\n\x04keys\x18\x1d \x01(\t\x12\r\n\x05notes\x18\x1e \x01(\t\x12\x30\n\x0clast_seen_at\x18\x1f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nscraped_at\x18  \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18! \x01(\x0b\x32\x1a.google.protobuf.TimestampB$Z\"github.com/opencars/schema/auctionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auction.auction_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"github.com/opencars/schema/auction'
  _AUCTION._serialized_start=99
  _AUCTION._serialized_end=820
# @@protoc_insertion_point(module_scope)
