# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auction/events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.auction import auction_pb2 as proto_dot_auction_dot_auction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/auction/events.proto\x12\x07\x61uction\x1a\x1bproto/auction/auction.proto\"2\n\rAuctionParsed\x12!\n\x07\x61uction\x18\x01 \x01(\x0b\x32\x10.auction.AuctionB$Z\"github.com/opencars/schema/auctionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auction.events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"github.com/opencars/schema/auction'
  _AUCTIONPARSED._serialized_start=68
  _AUCTIONPARSED._serialized_end=118
# @@protoc_insertion_point(module_scope)
