# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/event.proto\x12\x05proto\x1a\x19google/protobuf/any.proto\"Y\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1d\n\x06source\x18\x02 \x01(\x0b\x32\r.proto.Source\x12%\n\x07payload\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"\xae\x01\n\x03\x43UD\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.proto.CUD.Type\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12%\n\x07\x63urrent\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\x12$\n\x06\x63hange\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\"*\n\x04Type\x12\n\n\x06\x43REATE\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\"*\n\x06Source\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\tB\x1cZ\x1agithub.com/opencars/schemab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\032github.com/opencars/schema'
  _EVENT._serialized_start=55
  _EVENT._serialized_end=144
  _CUD._serialized_start=147
  _CUD._serialized_end=321
  _CUD_TYPE._serialized_start=279
  _CUD_TYPE._serialized_end=321
  _SOURCE._serialized_start=323
  _SOURCE._serialized_end=365
# @@protoc_insertion_point(module_scope)
